### ISSUE TITLE
Receiving TypeError

### ISSUE THREAD

**Issue by macelik** [vlasmirnov/GCM#13]
Hello there,

I am planning to run MAGUS on 600k sequences (S prot of Sars-CoV-2). I wanted to give it a quick try and downloaded influenza PB1 proteins and run MAGUS with `python ./MAGUS/magus.py -d outputs1 -i PB1.fasta -o aligned1.txt` but its keep failing, with an error `TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'` , although the example file run without errors. You can find the log files and fasta file in the below link. Could you help me with this?

[link to files](https://github.com/macelik/dump)

Thank you

**Comment by vlasmirnov** [comment]
Thanks a lot for reaching out and I'm sorry you had issues.
The problem with your input file are the special characters in sequence names - for example, the spaces seem to get cut off by FastTree, and the parentheses cause problems when they're put into newick strings. Underscores are usually fine, but it's best to keep the names as simple as possible. 

I renamed the sequences from >ATI21281.1 |polymerase PB1 [Influenza A virus (A/swine/Zhejiang/SW57/2015(H5N1))] to >ATI21281.1_polymerasePB1InfluenzaAvirusA_swine_Zhejiang_SW57_2015H5N1, and it finished without issues.

I'll work on doing conversions like this automatically within MAGUS, but please let me know if this helps you for now. (It may be practical to use the Clustal starting tree option if you're planning to run 600,000 sequences).

**Comment by macelik** [comment]
Thanks for the very quick reply. 

Yes, it worked just fine after removing the whitespaces from the headers. Yes, documentation is clear about the -t clustal parameter. I will definetely use it. 

Oh, just to let you know, I am running it on WSL2 and I needed to install dendropy( `pip install dendropy` ). Nothing major, but if you'd like to add it to your documentation.

Great work!

**Comment by vlasmirnov** [comment]
My pleasure, I'm glad it worked. Please let me know if you encounter any other difficulties going forward.
I'll update the documentation as well, thanks for the catch.
