### ISSUE TITLE
where to find mlrmcl

### ISSUE THREAD

**Issue by ptitle** [vlasmirnov/GCM#23]
Hi,
As I am working on a mac, I've been installing the dependencies myself. I have been able to track down all of them except for mlrmcl. Can you please provide a link?

Thanks!

**Comment by RuneBlaze** [comment]
Hey @ptitle . I think unless you were trying to replicate the GCM-MWT [paper](https://link.springer.com/chapter/10.1007/978-3-030-74432-8_12), you don't specifically need mlrmcl. Having a copy of mcl is enough 🙂 for the alignment merging step of GCM. So if you managed to find all the dependencies sans mrlmcl, you should be perfectly good!

Let me know if there is anything else I might be able to help with. (I am helping out Vlad here, the author of this package)

**Comment by ptitle** [comment]
So it's ok if not all the paths in the config file point to a functional program?
I'm only aiming to run MAGUS with the recommended strategies, not needing to run all alternatives.
thanks for your help!

**Comment by RuneBlaze** [comment]
Yeah @ptitle , I recall that running MAGUS in the default recommended strategies should only require valid binaries for FastTree (or Clustal, as a non-default, but sometimes still recommended decomposition tree to use), MAFFT, HMMER (hmmbuild, hmmsearch, hmmalign), and MCL. `mlrmcl` or `raxml` are not necessary unless you really want to try out alternatives strategies.

**Comment by ptitle** [comment]
ok great -- could be a worth a note in the documentation. Thanks again!

**Comment by RuneBlaze** [comment]
Hey @ptitle , thanks for reaching out, and yes, I do agree that it could be worth a note in the documentation! That's something I will pitch to @vlasmirnov (perhaps with an FAQ session)
